name = "chests"
description = "Chests are bounded containers"
version = "0.2.0"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]

licenses = "BSD-3-Clause"
website = "https://github.com/JeremyGrosser/chests"
tags = ["containers", "bounded", "nostd", "embedded"]

[origin]
commit = "742eabfff2d3bff353a0dac6f32d3d2cbe9c835e"
url = "git+https://github.com/JeremyGrosser/chests.git"

