name                        = "atari_atr_tools"
description                 = "Cross-platform tool for ATR disk images for Atari 8-bit systems"
long-description            = """Atari ATR Tools is a versatile, cross-platform utility written in Ada 2022 for managing ATR disk image files used by Atari 8-bit emulators (e.g., Altirra, Atari800) and hardware add-ons like SIO2PC. Unlike most existing tools, which are Windows-only, this tool runs seamlessly on macOS, Linux, and Windows, making it ideal for retro computing enthusiasts across all major platforms.

Key features include:

**Header Analysis**: Display detailed metadata of ATR files, including sector
size, disk density, track count, and boot sector presence.

```sh
  > atr_tools-main --print-header test-DD-DS-80.atr
  File name        : test-DD-DS-80.atr
  Magic            :      16#296#
  Paragraphs       :        46056
  Sector size      :          256
  Flags            :         2#1#
  Bad Sectors      :            0
  Unused           :        16#0#
  Sectors          :         2880
  Bytes            :       736896
  Boot Sectors     : true
  Floppy disk double density, double sided, 80 track
```

**Floppy Image Creation**: Format and create ATR files for various disk
configurations (e.g., single-sided, double-density, 80 tracks).

```sh
> atr_tools-main --verbose --format-floppy --density=DD --side=SS --track=80 test-DD-SS-80.atr
File created     : test-DD-SS-80.atr
Sector size      :          256
Sector per track :           18
Tracks per side  :           80
Sides per disk   :            1
```

The tool includes a comprehensive test suite to ensure reliability across platforms and configurations. Source code and tests are available on SourceForge. Detailed GNATdoc documentation can be found at [6502 Tutorial](https://tutorial-6502.sourceforge.io/gnatdoc/atr_tools/index.html).
"""
version                     = "1.5.1"
licenses                    = "GPL-3.0-or-later"
authors                     = ["Martin Krischik <krischik@users.sourceforge.net>"]
maintainers                 = ["Martin Krischik <krischik@users.sourceforge.net>"]
maintainers-logins          = ["krischik"]
executables                 = ["atr_tools-main"]
website                     = "https://sourceforge.net/projects/tutorial-6502"
tags                        = ["atari", "tools", "retrocomputing", "ada-2022"]

[build-switches]
"*".ada_version             = "Ada2022"
"*".source_encoding         = "UTF_8"
development.compile_checks  = "Warnings"
development.contracts       = "Yes"
development.debug_info      = "Yes"
development.optimization    = "Debug"
development.runtime_checks  = "Overflow"
release.compile_checks      = "Warnings"
release.contracts           = "No"
release.debug_info          = "No"
release.optimization        = "Performance"
release.runtime_checks      = "Default"
validation.compile_checks   = "Warnings"
validation.contracts        = "Yes"
validation.debug_info       = "Yes"
validation.optimization     = "Debug"
validation.runtime_checks   = "Everything"

[[depends-on]]
adacl                       = "^6.3.0"

[[actions]]
type                        = "test"
command                     = ["alr", "run"]
directory                   = "test"

# vim: set textwidth=0 nowrap tabstop=8 shiftwidth=4 softtabstop=4 expandtab :
# vim: set filetype=toml fileencoding=utf-8 fileformat=unix foldmethod=diff :
# vim: set spell spelllang=en_gb :

[origin]
hashes = [
"sha256:f83e01b4a70cb4ed38169c7aebd6eaa90a10f241d78b050bfaea55c3796c3e54",
"sha512:65ad2fe793d2fed8d1e12c2de7718ffcf997d602c5b0f4896af15197a24fe6f71359dc94d3c07f93e58e68f84cb5bc633062621ad682b0dca7271750792bc01e",
]
url = "https://sourceforge.net/projects/tutorial-6502/files/Alire/atari_atr_tools-1.5.1.tgz"

