name                        = "mos6502_create_nop"
description                 = "Create NOP ROM"
long-description            = """This is a tool to create a rom image with NOP commands.

This program can be used to create a ROM immage for the MOS 6502 tutorial from Ben Eater.

Development versions available with:

```sh
alr index --add "git+https://github.com/krischik/alire-index.git#develop" --name krischik
``` 

Source code and testsuite available on [SourceForge](https://git.code.sf.net/p/tutorial-6502/git)
"""
version                     = "1.1.2"
licenses                    = "GPL-3.0-or-later"
authors                     = ["Martin Krischik <krischik@users.sourceforge.net>"]
maintainers                 = ["Martin Krischik <krischik@users.sourceforge.net>"]
maintainers-logins          = ["krischik"]
executables                 = ["create_nop"]
website                     = "https://sourceforge.net/projects/tutorial-6502"
tags                        = ["mos-6502", "tools", "retrocomputing", "ada2022"]

[[depends-on]]
gnat                        = ">=12 & <2000"

[[actions]]
type                        = "test"
command                     = ["alr", "run"]
directory                   = "test"

# vim: set textwidth=0 nowrap tabstop=8 shiftwidth=4 softtabstop=4 expandtab :
# vim: set filetype=toml fileencoding=utf-8 fileformat=unix foldmethod=diff :
# vim: set spell spelllang=en_gb :

[origin]
hashes = [
"sha256:fbfe6f5d7946955ddeb563b9e3c8165d2b7ef86f0032ecb6dd007d13fd18f785",
"sha512:e36eef13e354e39fd04da74305f6944261d7f27a38aaf22e587c865873deaaf5a6531a6ec23d39489b103caab35b0c77260fcf8bdf6eb311c2de7c4f4b123347",
]
url = "https://sourceforge.net/projects/tutorial-6502/files/Alire/mos6502_create_nop-1.1.2.tgz"

