name = "win32ada"
version = "23.0.0"
description = "Ada API to the Windows library"
long-description = """\
Due to a subpar integration of Win32Ada in Alire, any project using Win32Ada
specs must also have the Win32Ada pre-processing switches. 

Do this edit your GPR project file to:
1. With the "shared" project from Win32Ada: `with "shared.gpr";`
2. Add the following switches for Ada: `(Shared.Prep, "-gnateG");`

Here's what it looks like in an example project:
```ada
with "config/test_win32_config.gpr";

with "shared.gpr";

project Test_Win32 is

   for Source_Dirs use ("src/", "config/");
   for Object_Dir use "obj/" & Test_Win32_Config.Build_Profile;
   for Create_Missing_Dirs use "True";
   for Exec_Dir use "bin";
   for Main use ("test_win32.adb");

   package Compiler is
      for Default_Switches ("Ada") use
        Test_Win32_Config.Ada_Compiler_Switches &
        (Shared.Prep, "-gnateG"); -- See this line here
   end Compiler;

   package Binder is
      for Switches ("Ada") use ("-Es");
   end Binder;

   package Install is
      for Artifacts (".") use ("share");
   end Install;

end Test_Win32;
```

"""
website = "https://github.com/adacore/win32ada"
authors = ["Intermetrics", "AdaCore"]
maintainers = ["chouteau@adacore.com"]
maintainers-logins = ["Fabien-Chouteau"]
tags = ["windows", "api"]

[configuration]
disabled = true

[gpr-externals]
PRJ_TARGET = ["Win32", "Win64"]
PRJ_BUILD = ["Debug", "Release"]

[available.'case(os)']
windows = true
'...'   = false

[gpr-set-externals]
TARGET = "Win64"
PRJ_TARGET = "Win64"
PRJ_BUILD = "Release"

[origin]
url= "https://github.com/AdaCore/win32ada/archive/v23.0.0/win32ada-23.0.0.zip"
hashes=['sha512:680108e6097837aa85403e0a7c9045380eb979187faf4400f1537502d3e224edf7a6f9e1f351783901e1b7d815c61b5cfcb7df8b1bf93c1670df280b32ca41a1']
