name = "edc_client"
description = "Client library for: github.com/hgrodriguez/embedded-dashboard-console"
version = "1.5.2"
licenses = "BSD-3-Clause"

authors = ["Holger Rodriguez"]
maintainers = ["Holger Rodriguez <github@roseng.ch>"]
maintainers-logins = ["hgrodriguez"]
tags = ["embedded", "rp2040"]
website = "https://github.com/hgrodriguez/edc_client"

[[depends-on]]  # Added by alr
hal = "^1"  # Added by alr

[origin]
commit = "04967d941362fc9aa6a923f08738e607c21ba063"
url = "git+https://github.com/hgrodriguez/edc_client.git"

