name = "muntsos_aarch64"
description = "MuntsOS Embedded Linux support for AArch64 targets"
tags = ["muntsos", "embedded", "linux", "arm64", "aarch64"]
version = "10.4.0"
website = "https://github.com/pmunts/muntsos"
authors = ["Philip Munts"]
maintainers = ["Philip Munts <phil@munts.net>"]
maintainers-logins = ["pmunts"]

long-description = """
# Introduction

This crate modifies an Alire program project to build a cross-compiled
program for a **[MuntsOS Embedded
Linux](https://github.com/pmunts/muntsos)** AArch64 / ARMv8 / arm64
target computer.

The **MuntsOS Embedded Linux** cross toolchain packages must be
installed on your Linux development computer before you can use this
crate. See [Application Note
#1](https://repo.munts.com/muntsos/doc/AppNote1-Setup-Debian.pdf) for
Debian distributions or [Application Note
#2](https://repo.munts.com/muntsos/doc/AppNote2-Setup-RPM.pdf) for RPM
distributions.

Each **MuntsOS Embedded Linux** cross toolchain contains prebuilt **[Ada
Web Server](https://github.com/AdaCore/aws)** and **[Linux Simple I/O
Library](https://github.com/pmunts/libsimpleio)** components. Therefore,
**DO NOT** attempt to **alr with** any of the **aws**, **libsimpleio**,
**mcp2221**, **remoteio**, **wioe5_ham1**, **wioe5_ham2**, or
**wioe5_p2p** crates in a project using this crate.

# Environment Variables

If **ALIRE_DISABLESTYLECHECKS** is set to **yes**, the postfetch script
will disable style checking in the project **.gpr** file.

If **ALIRE_INSTALLMAKEFILE** is set to **yes**, the postfetch script
will install an optional but useful **Makefile** to the project
directory.

You can add the following to **~/.bashrc** or its equivalent to
permanently define these environment variables:

    export ALIRE_DISABLESTYLECHECKS=yes
    export ALIRE_INSTALLMAKEFILE=yes

# Example

The following commands illustrate how to create an Alire program project
that will cross-compile a program to run on a **MuntsOS Embedded Linux**
target computer. The result is a pristine (*i.e.* all temporary, working
and deliverable files removed) project, suitable for checking into a
source code control repository.

    alr -n init --bin myexample
    cd myexample
    alr -n with muntsos_aarch64
    ALIRE_DISABLESTYLECHECKS=yes ALIRE_INSTALLMAKEFILE=yes alr action -r post-fetch
    make reallyclean

See also [Application Note
#7](https://repo.munts.com/muntsos/doc/AppNote7-Flash-LED-Ada-Alire.pdf).
"""

project-files = ["aws.gpr", "libsimpleio.gpr"]

[available."case(os)"]
"linux" = true
"..." = false

[configuration]
disabled = true

[[depends-on]]
muntsos_dev_aarch64 = "*"

[[actions]]
type = "post-fetch"
command = ["sh", "-c", "./postfetch"]

[origin]
hashes = [
"sha256:c6faa7aa5d4cf1a008bb535801eceab3bab867f596ac9025d73bc01ec0c1932b",
"sha512:74e1d9639463f0b288697faeb1d9a577492272f4015bb779a1f12165c09bc9f88e8e8a6e242317b5a1dbfa0d7278f19d0ef5376c271326239c0f01f5733873ee",
]
url = "https://raw.githubusercontent.com/pmunts/alire-crates/ab66f23f09ad44ed0124f97a2ea15b58ad4e2b78/muntsos_aarch64/muntsos_aarch64-10.4.0.tbz2"

