description = "Simple DirectMedia Layer development files - Image"
name = "libsdl2_image"

maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]

[[external]]
kind = "system"
    [external.origin.'case(distribution)']
    'debian|ubuntu' = ["libsdl2-image-dev"]
    'arch' = ["sdl2_image"]
    'centos' = ["SDL2_image-devel"]
    'fedora' = ["SDL2_image-devel"]
    'homebrew' = ["sdl2_image"]
    'macports' = ["libsdl2_image"]
    'gentoo' = ["media-libs/sdl2-image"]
    'msys2' = ["mingw-w64-x86_64-SDL2_image"]
