name = "coap_client"
description = "Client program for the CoAP-SPARK library"
version = "0.9.0"

authors = ["Manuel Gomez"]
maintainers = ["Manuel Gomez <mgrojo@gmail.com>"]
maintainers-logins = ["mgrojo"]
licenses = "Apache-2.0 OR GPL-2.0-or-later"
website = "https://github.com/mgrojo/coap_spark"
tags = ["coap", "spark", "client", "iot", "protocol"]

executables = ["coap_client"]

[[depends-on]]
coap_spark = "^0.9.0"

[build-switches]
"*".Style_Checks = ["-gnatyC"]
"*".Ada_Version = "Ada2022"

[origin]
url = "git+https://github.com/mgrojo/coap_spark.git"
commit = "3dc855f1cf5c730b512c9c782c82973a10f95c81"
subdir = "client"