name = "pager2"
description = "Manipulate \"paged files\" found on the Ada Software Repository"
version = "2.0.1"

authors = ["Richard Conn"]
maintainers = ["Darren Bane <darren.bane.ac@posteo.net>"]
maintainers-logins = ["poldy"]
licenses = "custom-CC-PDM-1.0"
website = "https://chiselapp.com/user/dbane/repository/pager2"
tags = ["application", "archive"]

[origin]
hashes = [
"sha256:937c306e3fa800f156c5aea142898f17fe2ee18481267eccc5db8ecfbacb6bd5",
"sha512:5b904ca8d2fe609b3d99dcaaeb354211a90964a2c4e5dda9f93bcdee6b157f3cf90535a0557b91803d8ee016e0cc877389b9e8beba2223a025371497f4f896f8",
]
url = "https://chiselapp.com/user/dbane/repository/pager2/tarball/98275eae74/pager2-98275eae74.tar.gz"

