description = "Board Support Package for the BBC micro:bit v1"
long-description = '''# microbit BSP

Board Support Package for the BBC micro:bit https://microbit.org/

This crate is a snapshot of [Ada Drivers
Library](https://github.com/AdaCore/Ada_Drivers_Library/tree/master/middleware).

Any bug report, issue, contribution must be adressed to the [Ada Drivers
Library](https://github.com/AdaCore/Ada_Drivers_Library/) repo.

'''

name = "microbit_bsp"
version = "0.2.1"
licenses = "BSD-3-Clause"
website="https://github.com/AdaCore/Ada_Drivers_Library/"
maintainers = ["chouteau@adacore.com"]
maintainers-logins = ["Fabien-Chouteau"]
project-files = ["microbit_bsp.gpr"]
tags = ["embedded", "nostd", "microbit", "bbc", "nrf51", "bsp"]

[[depends-on]]
hal = "~0.1.0"
nrf5x_hal = "~0.1.0"
embedded_components = "~0.1.0"

[build-switches]
"*".style_checks = "no"
[origin]
commit = "6e957aa83afff9c164f1eb68f5fb5a59cc94ac45"
url = "git+https://github.com/Fabien-Chouteau/microbit_bsp.git"

