name = "light_tasking_nrf52832"
description = "light-tasking runtime for the nRF52832 SoC"
version = "15.0.0"

long-description = """
## Usage

First edit your `alire.toml` file and add the following elements:
 - Add `light_tasking_nrf52832` in the dependency list:
   ```toml
   [[depends-on]]
   light_tasking_nrf52832 = "*"
   ```

Then edit your project file to add the following elements:
 - "with" the run-time project file. With this, gprbuild will compile the run-time before your application
   ```ada
   with "runtime_build.gpr";
   ```
 - Specify the `Target` and `Runtime` attributes:
   ```ada
      for Target use runtime_build'Target;
      for Runtime ("Ada") use runtime_build'Runtime ("Ada");
   ```
"""

authors = ["AdaCore", "Daniel King"]
maintainers = ["Daniel King <damaki.gh@gmail.com>"]
maintainers-logins = ["damaki"]
licenses = "GPL-3.0-or-later WITH GCC-exception-3.1"
tags = ["embedded", "runtime"]
website = "https://github.com/damaki/nrf52-runtimes"

project-files = ['runtime_build.gpr', 'ravenscar_build.gpr']

[configuration]
generate_gpr = false
generate_c = false
output_dir = "gnat_user"

[configuration.variables]
Time_Base = { type = "Enum", values = ["RTC0", "RTC1", "RTC2"], default = "RTC2" }
LFCLK_Src = { type = "Enum", values = ["Xtal", "RC", "Synth"], default = "Xtal" }
Use_SWO_Trace = { type = "Boolean", default = true }
Use_Reset_Pin = { type = "Boolean", default = true }

[[depends-on]]
gnat_arm_elf = "^15"

[origin]
hashes = [
"sha256:3cc23a66284771f432d02dd5cc5467a3d6fecd13465b7fdd784842bb7e08b159",
"sha512:d04f105df11aea41bf769b2b45bf92764a4f20f4ffd6336961f0cc7f946e6c6309691f332bbbad9dc0359ffceafa189c63e1c95cb8170e0df203d8916280ba16",
]
url = "https://github.com/damaki/nrf52-runtimes/releases/download/v15.0.0/light-tasking-nrf52832-15.0.0.tar.gz"

