name = "astro"
description = "Library for astronomical calculations"
version = "1.3.0"

authors = ["Juan A. de la Puente"]
maintainers = ["Juan A. de la Puente <juan.de.la.puente@upm.es>"]
maintainers-logins = ["jpuente"]
licenses = "GPL-3.0-or-later"
website = "https://github.com/jpuente/almanac/tree/master/astro"
tags = ["astronomy", "sun", "moon", "planets"]

[[ depends-on ]]
ephemeris = "~1.1.0"


[origin]
commit = "f8d89b7e7fdeeeb2544b5716a4e2afee3a511d04"
subdir = "./astro/"
url = "git+https://github.com/jpuente/almanac.git"

