name = "swan"
description = "Stuff We All Need - utilities collection for ada"
version = "0.1.0"

authors = ["Matheus Xavier"]
maintainers = ["Matheus Xavier <mxavierdev@gmail.com>"]
maintainers-logins = ["xadaemon"]
licenses = "Apache-2.0"
website = "https://github.com/xadaemon/swan_ada"
tags = ["utilities", "buffers", "collections"]

[origin]
commit = "2a1b9f756da6083f86dfc541d0d228c1a3844656"
url = "git+https://github.com/xadaemon/swan_ada.git"

