name = "ptf"
description = "Portable Text Formatter"
version = "1.2"

authors = ["Darren Bane"]
maintainers = ["Darren Bane <darren.bane.ac@posteo.net>"]
maintainers-logins = ["poldy"]
licenses = "custom-CC-PDM-1.0"
website = ""
tags = ["documentation", "tools"]

[origin]
hashes = [
"sha256:91016114d9b09363610a1d5a6cad7ac3ff0ff8598ebbf3d36fcbc1a3f6edd319",
"sha512:592f3943d1b229f832ad57978e5be58d40b03259ec0623394cde97d27b49e808a2b9e6cfa188537ce1ba9f5fdcdf5361f921fe11a929f44c8b394b243399d74e",
]
url = "https://chiselapp.com/user/dbane/repository/ptf/tarball/c2ac25d523/ptf-c2ac25d523.tar.gz"

