description = "LEA is a Lightweight Editor for Ada "
name = "lea"
version = "0.92.1"

authors = ["Gautier de Montmollin"]
website = "https://github.com/zertovitch/lea"
licenses = "MIT"
tags = ["application", "lea", "editor", "hac"]
maintainers = ["gdemont@hotmail.com"]
maintainers-logins = ["zertovitch"]

long-description = """
&nbsp; <a target="_blank" href="https://a.fsdn.com/con/app/proj/l-e-a/screenshots/sudo_new-0c7d4c58.png"    ><img src="https://a.fsdn.com/con/app/proj/l-e-a/screenshots/sudo_new-0c7d4c58.png"     alt="lea screenshot 1" width="auto" height="140"></a>
&nbsp; <a target="_blank" href="https://a.fsdn.com/con/app/proj/l-e-a/screenshots/mandel_new-f3219868.png"  ><img src="https://a.fsdn.com/con/app/proj/l-e-a/screenshots/mandel_new-f3219868.png"   alt="lea screenshot 2" width="auto" height="140"></a>
&nbsp; <a target="_blank" href="https://a.fsdn.com/con/app/proj/l-e-a/screenshots/lea_ubu-912c5456.png"     ><img src="https://a.fsdn.com/con/app/proj/l-e-a/screenshots/lea_ubu-912c5456.png"      alt="lea screenshot 3" width="auto" height="140"></a>
&nbsp; <a target="_blank" href="https://a.fsdn.com/con/app/proj/l-e-a/screenshots/ext_edit_new-28fcf374.png"><img src="https://a.fsdn.com/con/app/proj/l-e-a/screenshots/ext_edit_new-28fcf374.png" alt="lea screenshot 4" width="auto" height="140"></a>

**LEA**, a **Lightweight Editor for Ada**, aims to provide an easy, script-world-like, "look & feel" for developing Ada projects of any size and level, while enabling access to full-scale development tools like GNAT.

Features:

* Quick start and reactivity
* Uses the Scintilla editor widget (like Notepad++)
* Multi-document
* Multiple undo's & redo's
* Multi-line, multi-point editing; rectangular selections
* Duplication of lines and selections
* Color themes
* Syntax highlighting, parenthesis matching
* Bookmarks
* Smart editor features (auto-completion, navigation, mouse-hover infos)
* Includes HAC, the HAC Ada Compiler
* Includes numerous examples of Ada programs, ready to be run
* Single executable, runs without installation
* Programmed in Ada
* **Free**, Open-Source
"""

project-files = ["lea_project_tree.gpr"]
executables = ["lea"]

[available.'case(os)']
windows = true
'...' = false

[gpr-externals]
LEA_Build_Mode = ["Debug", "Fast", "Small"]

[gpr-set-externals]
HAC_Build_Mode = "Small"
LEA_Build_Mode = "Small"
Zip_Build_Mode = "Small"

[[depends-on]]
ini_files = "^10.0.0"
[[depends-on]]
gwindows = "^1.5.0"
[[depends-on]]
zipada = "^61.0.0"
[[depends-on]]
gnat = "/=10.3.2"
[[depends-on]]
hac = "0.41.0"

[[actions.'case(os)'.windows]]
type = "post-build"
command = ["cmd", "/c copy /B lea_without_data.exe + _lea_data.zip lea.exe"]

[origin]
url = "https://sourceforge.net/projects/l-e-a/files/lea-src-v.0.92.zip"
hashes = ["sha512:2e2a83184bb7eb71ca626c1a1fe0c1a13a69f0d3b3ad58dd20d50660be80169c1066d76865527d9f3482c1e5bff846ac294e245cf33d6d9371dc9b5e137c5e47"]
