name = "a0b_armv7m"
description = "ARMv7-M support (Cortex-M3, Cortex-M4, Cortex-M7)"
website = "https://github.com/godunko/a0b-armv7m"
version = "0.4.0"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"

project-files=["gnat/a0b_armv7m.gpr"]

tags = ["a0b", "embedded", "armv7m", "cortex-m", "cortex-m3", "cortex-m4", "cortex-m7"]

[configuration.variables]
FPU_Extension = {type = "Enum", values = ["undefined", "none", "VFPv4", "VFPv5"], default="undefined"}
# This configuration varible is not used by the crate, and it is not clear now should, or should not be preserved.

[configuration]
generate_ada = false
generate_gpr = true
generate_c = false

[[depends-on]]
a0b_base = "*"
gnat_arm_elf = "*"

[[actions]]
type = "test"
directory = "selftest"
command = ["alr", "build"]

[origin]
commit = "bb8b0af2ed2c64f2381ad5c7953bfa2b88b0c4da"
url = "git+https://github.com/godunko/a0b-armv7m.git"

