name = "a0b_base"
description = "A0B: Base components"
website = "https://github.com/godunko/a0b-base"
version = "0.4.0"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["a0b", "types", "builtins"]

project-files=["gnat/a0b_base.gpr"]

[configuration]
generate_ada = false
generate_gpr = true
generate_c = false

[configuration.variables]
Tasking = {type = "Enum", values = ["none", "ada", "a0b"], default = "none"}

[origin]
commit = "a7acf07031a63eb9d31d51f2bf28dab0799ab5c5"
url = "git+https://github.com/godunko/a0b-base.git"

