name = "yeison_12"
description = "A JSON-like data structure (Ada 2012 version)"
version = "0.2.0"
licenses = "MIT"

authors = ["Alejandro R. Mosteo"]
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]
tags = ["json", "yaml", "toml", "containers"]
website = "https://github.com/mosteo/yeison"

[build-switches]
"*".ada_version = "Ada12"

[origin]
commit = "20033cf90a3eb2eff69d9ff9d0820291aed79b57"
subdir = "./yeison_12/"
url = "git+https://github.com/mosteo/yeison.git"

