name = "light_nrf52840"
description = "light runtime for the nRF52840 SoC"
version = "15.0.0"

long-description = """
## Usage

First edit your `alire.toml` file and add the following elements:
 - Add `light_nrf52840` in the dependency list:
   ```toml
   [[depends-on]]
   light_nrf52840 = "*"
   ```

Then edit your project file to add the following elements:
 - "with" the run-time project file. With this, gprbuild will compile the run-time before your application
   ```ada
   with "runtime_build.gpr";
   ```
 - Specify the `Target` and `Runtime` attributes:
   ```ada
      for Target use runtime_build'Target;
      for Runtime ("Ada") use runtime_build'Runtime ("Ada");
   ```
"""

authors = ["AdaCore", "Daniel King"]
maintainers = ["Daniel King <damaki.gh@gmail.com>"]
maintainers-logins = ["damaki"]
licenses = "GPL-3.0-or-later WITH GCC-exception-3.1"
tags = ["embedded", "runtime"]
website = "https://github.com/damaki/nrf52-runtimes"

project-files = ['runtime_build.gpr']

[configuration]
generate_gpr = false
generate_c = false
output_dir = "gnat_user"

[configuration.variables]
Time_Base = { type = "Enum", values = ["RTC0", "RTC1", "RTC2"], default = "RTC2" }
LFCLK_Src = { type = "Enum", values = ["Xtal", "RC", "Synth"], default = "Xtal" }
Use_SWO_Trace = { type = "Boolean", default = true }
Use_Reset_Pin = { type = "Boolean", default = true }

[[depends-on]]
gnat_arm_elf = "^15"

[origin]
hashes = [
"sha256:a37c655e3c45fdd153316a7a9cbc2d81bea35067c00b2fb8c73d60ebff3adcd4",
"sha512:0649de12aa2db86fd10028f2f719aeec49393346aa3a518b776432550116f3a5a43760f31df671e32b2a78dda448f10df01b7aaf1189751d0f7d09c82097d1f2",
]
url = "https://github.com/damaki/nrf52-runtimes/releases/download/v15.0.0/light-nrf52840-15.0.0.tar.gz"

