name = "softdev"
description = "Serial protocols implemented in software"
version = "1.0.0"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]
licenses = "BSD-3-Clause"
website = "https://github.com/JeremyGrosser/softdev"
tags = ["embedded", "i2c"]

[[depends-on]]
hal = "^1"

[origin]
commit = "b5d1c8ed0beef9c532e17a883b80e674a410d11b"
url = "git+https://github.com/JeremyGrosser/softdev.git"

