description = "Produce Excel spreadsheets"
name = "excel_writer"
version = "19.0.1"
authors = ["Gautier de Montmollin"]
website = "https://excel-writer.sourceforge.io/"
licenses = "MIT"
maintainers = ["gdemont@hotmail.com"]
maintainers-logins = ["mosteo", "zertovitch"]
project-files = ["excel_out.gpr"]
executables = ["excel_out_demo"]
tags = ["excel", "spreadsheet", "xls", "csv"]

long-description = """
![Excel Writer logo](https://excel-writer.sourceforge.io/ew_logo_no_shadow.png)

Excel_Out is a standalone, portable Ada package for writing Excel spreadsheets with basic formattings and formulas, easily and programmatically.

* Enables the automatic production of reports
* Fast: 50 sheets per second, with 10,000 data cells each on a slow 1.66 GHz computer
* No interaction needed with Excel or MS Office
* Unconditionally portable (*)
* Endian-neutral
* Object oriented
* Task safe
* Pure Ada 95 (nothing compiler/system specific), can be used in projects in Ada 95, Ada 2005, Ada 2012 and later versions of the language
* Floating-point hardware neutral: no IEEE hardware required
* Tests and demos included
* Includes a CSV parser with related tools.
* Free, open-source

The creation of an Excel file is as simple as this small procedure:

```ada
with Excel_Out;

procedure Small_Demo is
  xl : Excel_Out.Excel_Out_File;
begin
  xl.Create ("small.xls");
  xl.Put_Line ("This is a small demo for Excel_Out");
  for row in 3 .. 8 loop
    for column in 1 .. 8 loop
      xl.Write (row, column, row * 1000 + column);
    end loop;
  end loop;
  xl.Close;
end Small_Demo;
```

___

(*) within limits of compiler's provided integer types and target architecture capacity.
"""

[origin]
url = "https://sourceforge.net/projects/excel-writer/files/excel-writer/excel_writer_19_01.zip"
hashes = ["sha512:a337fb5bb75c062efebd7f35687e5ff7958c93b27a16a4d9fcf9531eb01138dc77432784281a8dbbf0cf6af46c273f28582e11612998108cfa3ebbe5e8971761"]
