name = "uxstrings"
description = "Unicode Extended Strings utilities"
version = "0.9.0+alpha-20250903"
tags = ["unicode", "dynamic", "string"]

authors = ["Pascal Pignard"]
maintainers = ["Pascal Pignard <blady.net@orange.fr>"]
maintainers-logins = ["Blady-Com"]
website = "https://github.com/Blady-Com/UXStrings"

licenses = "CECILL-C"

project-files = ["lib_uxstrings.gpr"]

[[depends-on]]
gnat = ">=13"
# Put in comment since dependancies of SC puzzled Alire
# simple_components = "^4.62.0"

[origin]
commit = "04400aa894d62a543065f0df841695fba52e201d"
url = "git+https://github.com/Blady-Com/UXStrings.git"

