description = "Portable package for producing dynamically PDF documents"
name = "apdf"
version = "8.0.0"
authors = ["Gautier de Montmollin"]
website = "https://github.com/zertovitch/ada-pdf-writer"
licenses = "MIT"
maintainers = ["gdemont@hotmail.com"]
maintainers-logins = ["zertovitch", "Fabien-Chouteau"]
project-files = ["pdf_out_w_gid.gpr"]
executables = ["pdf_out_demo", "koch_curve", "sierpinski_arrowhead_curve"]
tags = ["pdf", "adobe", "acrobat"]

long-description = """

**PDF_Out** is an Ada package for producing easily and automatically PDF files, from an Ada program, with text, vector graphics and raster graphics.

![Ada PDF Screenshot](https://apdf.sourceforge.io/pw_ari_delivery_m.png "Screenshot of a page produced by PDF_Out")
![Ada PDF Screenshot](https://apdf.sourceforge.io/pw_sowebio_m.jpg      "Screenshot of a report produced by PDF_Out")

* Ideal for the dynamic production of reports, invoices, tickets, labels, delivery notes, charts, maps etc.
* Vector graphics
* Inclusion of JPEG images
* Object oriented
* Task safe
* Endian-neutral
* Multi-platform, but native code build
* Unconditionally portable code: OS-, CPU-, compiler- independent code
* Pure Ada 2012: this package can be used in projects in Ada 2012 and later language versions
* *Free*, open-source 

The creation of a PDF file is as simple as this small procedure:

```ada
with PDF_Out;

procedure Small_Demo is
  pdf : PDF_Out.PDF_Out_File;
begin
  pdf.Create ("small.pdf");
  pdf.Put_Line ("This is a very small demo for PDF_Out...");
  pdf.Close;
end Small_Demo;
```

"""

[gpr-externals]
PDF_Build_Mode = ["Debug", "Fast"]

[[depends-on]]
gid = ">=13.0.1"

[origin]
url = "https://sourceforge.net/projects/apdf/files/apdf_008.zip"
hashes = ["sha512:7dddb047dc67854f9c0879715704f66dda3ea19c31bf4f81f5de91b72a9367720d3f170131ea61e380acffc5a2f0d3bcb0d2bf31ffb8376173be293514851d1c"]
