name = "a0b_tools"
description = "A0B Tools: Runtime Generator"
website = "https://github.com/godunko/a0b-tools"
version = "0.1.0"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "GPL-3.0-or-later"

project-files=["gnat/a0b_tools.gpr"]
executables=["a0b-runtime"]
auto-gpr-with=false

tags = ["a0b", "tools", "runtime"]

[configuration]
generate_ada = false
generate_gpr = true
generate_c = false

[environment]
PATH.append = "${CRATE_ROOT}/bin"

[[depends-on]]
a0b_base = "*"
gnat = "*"
gnatcoll = "*"
vss = "*"


[origin]
commit = "39e79120e51c646cd330e77cc38f359b81ee6194"
url = "git+https://github.com/godunko/a0b-tools.git"

