name = "ltp_305"
description = "Driver for Pimoroni LED"
version = "1.0.0"
licenses = "BSD-3-Clause"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>", "Holger Rodriguez <github@roseng.ch>"]
maintainers-logins = ["JeremyGrosser", "hgrodriguez"]

tags = ["embedded", "led", "rp2040", "i2c"]
website = "https://github.com/hgrodriguez/ltp_305"

[[depends-on]]
hal = "^1"

[origin]
commit = "f0f09ffb3a47828dca671698c832eb69a0c15ebc"
url = "git+https://github.com/hgrodriguez/ltp_305.git"

