name = "ltp_305"
description = "Driver for Pimoroni LED"
version = "1.1.0"
licenses = "BSD-3-Clause"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>", "Holger Rodriguez <github@roseng.ch>"]
maintainers-logins = ["JeremyGrosser", "hgrodriguez"]

tags = ["embedded", "led", "rp2040", "i2c"]
website = "https://github.com/hgrodriguez/ltp_305"

[[depends-on]]
hal = "^1"

[origin]
commit = "861fb30017acf0a3b86add4abfee358d564f373f"
url = "git+https://github.com/hgrodriguez/ltp_305.git"

