name = "a0b_stm32g4"
description = "A0B: STM32G4 base support"
version = "0.1.0"

website = "https://github.com/godunko/a0b-stm32g4"
authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["a0b", "embedded", "stm32", "stm32g4"]

project-files = ["gnat/a0b_stm32g4.gpr"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = true

[[depends-on]]
a0b_armv7m="*"

[[actions]]
type = "test"
directory = "selftest"
command = ["alr", "build"]

[origin]
commit = "b78590b950a83ffaef2626d112dbf6979b99c80d"
url = "git+https://github.com/godunko/a0b-stm32g4.git"

