name                        = "adacl_eastrings"
description                 = "AdaCL: Encoding-Aware String Utilities"
long-description            = """Encoding-aware string utilities for Ada 2022, developed by Björn Persson for robust internationalization (i18n).

Supports text processing with the following encodings:
- Universal Character Set 4, Big-Endian (UCS-4 BE)
- Universal Character Set 4, Little-Endian (UCS-4 LE)
- Universal Character Set 2, Big-Endian (UCS-2 BE)
- Universal Character Set 2, Little-Endian (UCS-2 LE)
- Unicode Transformation Format 16, Big-Endian (UTF-16 BE)
- Unicode Transformation Format 16, Little-Endian (UTF-16 LE)
- Unicode Transformation Format 8 (UTF-8)
- American Standard Code for Information Interchange (ASCII)
- ISO/IEC 8859-1 (Latin-1)
- Code Page 850 (DOS Latin-1)
- Windows Code Page 1252

Additional features:
- Text I/O for encoding-aware input/output
- Basic command-line parsing for internationalized text

Licensed under GPL-3.0-or-later. Integrates with the Ada Class Library (AdaCL).

Source: [SourceForge](https://sourceforge.net/p/adacl/git/ci/master/tree/adacl_eastrings/src/)
Documentation: [GNATdoc](https://adacl.sourceforge.net/gnatdoc/adacl_eastrings/index.html)
"""
version                     = "7.0.0"
licenses                    = "GPL-3.0-or-later"
authors                     = ["Martin Krischik <krischik@users.sourceforge.net>" ,"Björn Persson <rombobeorn@users.sourceforge.net>"]
maintainers                 = ["Martin Krischik <krischik@users.sourceforge.net>" ,"Björn Persson <rombobeorn@users.sourceforge.net>"]
maintainers-logins          = ["krischik", "rombobeorn"]
website                     = "https://sourceforge.net/projects/adacl/"
tags                        = ["library", "strings", "i18n", "ada2022"]

[build-switches]
"*".ada_version             = "Ada2022"
"*".source_encoding         = "UTF_8"
development.compile_checks  = "Warnings"
development.contracts       = "Yes"
development.debug_info      = "Yes"
development.optimization    = "Debug"
development.runtime_checks  = "Overflow"
release.compile_checks      = "Warnings"
release.contracts           = "No"
release.debug_info          = "No"
release.optimization        = "Performance"
release.runtime_checks      = "Default"
validation.compile_checks   = "Warnings"
validation.contracts        = "Yes"
validation.debug_info       = "Yes"
validation.optimization     = "Debug"
validation.runtime_checks   = "Everything"

[[depends-on]]
adacl                       = "^7.0.0"


[origin]
hashes = [
"sha256:fa8bce5a25dbaf8589dff2523d57e2b39ea8e2bbcf8641ec80ddeaa564936905",
"sha512:18a4dbd59da585c9daf6a979b7ed8a9fe4cda2dfcbbb9a8102a2e8cef1e7f79b0870efbf7da7a101651e41a9276ec44b702f0c18670af2ae2df8e029fca3b219",
]
url = "https://sourceforge.net/projects/adacl/files/Alire/adacl_eastrings-7.0.0.tgz"

