name                        = "adacl_eastrings"
description                 = "Ada Class Library - EAStrings"
long-description            = """A class library for Ada for those who like OO programming.

Encoding aware strings.

Development versions available with:

```sh
alr index --add "git+https://github.com/krischik/alire-index.git#develop" --name krischik
```

Source code including AUnit tests available on [SourceForge](https://git.code.sf.net/p/adacl/git)
"""
version                     = "6.2.0"
licenses                    = "GPL-3.0-or-later"
authors                     = ["Martin Krischik <krischik@users.sourceforge.net>" ,"Björn Persson <rombobeorn@users.sourceforge.net>"]
maintainers                 = ["Martin Krischik <krischik@users.sourceforge.net>" ,"Björn Persson <rombobeorn@users.sourceforge.net>"]
maintainers-logins          = ["krischik", "rombobeorn"]
website                     = "https://sourceforge.net/projects/adacl/"
tags                        = ["library", "strings", "i18n", "ada2022"]

[build-switches]
development.compile_checks  = "Warnings"
development.contracts       = "Yes"
development.runtime_checks  = "Overflow"
release.compile_checks      = "Warnings"
release.contracts           = "No"
release.runtime_checks      = "Default"
validation.compile_checks   = "Warnings"
validation.contracts        = "Yes"
validation.runtime_checks   = "Everything"

[[depends-on]]
gnat_native                 = "^14.2"
adacl                       = "^6.1.1"

[[actions]]
type                        = "test"
command                     = ["alr", "run"]
directory                   = "test"

# vim: set textwidth=0 nowrap tabstop=8 shiftwidth=4 softtabstop=4 expandtab :
# vim: set filetype=toml fileencoding=utf-8 fileformat=unix foldmethod=diff :
# vim: set spell spelllang=en_gb :

[origin]
hashes = [
"sha256:7d32d817834417050cae64aefc8a3f394004ff47bf47469b46d3519dd111e569",
"sha512:7ed506c843374878d4a38d0a43639db498d6ee65f3e59025b1b12baa26376d3cbb27135550efbf2301bcf341384bd3d4f560ff395b4906daf9b1ba874330db59",
]
url = "https://sourceforge.net/projects/adacl/files/Alire/adacl_eastrings-6.2.0.tgz"

