name = "jintp"
description = "Template parser in Ada based on Jinja2"
version = "1.0.0"

authors = ["Rene Hartmann"]
maintainers = ["Rene Hartmann <rhartmann@users.sourceforge.net>"]
maintainers-logins = ["rehartmann"]
licenses = "BSD-2-Clause"
website = "https://github.com/rehartmann/JinTP"
tags = ["templates", "jinja", "jinja2"]

[origin]
commit = "ff347053d08d060c289b3d8d59cd39a77df67a86"
url = "git+https://github.com/rehartmann/JinTP.git"

