description = "Manage Zip Archives and raw BZip2 and LZMA streams"
name = "zipada"
version = "61.0.0"

authors = ["Gautier de Montmollin"]
website = "https://github.com/zertovitch/zip-ada"
licenses = "MIT"
tags = ["zip", "archive", "compression", "deflate", "lzma", "bzip2", "lzw", "shrink"]
maintainers = [ "gdemont@hotmail.com" ]
maintainers-logins = [ "mosteo", "zertovitch" ]

long-description = """
![Zip-Ada logo](https://unzip-ada.sourceforge.io/za_logo.png)

Zip-Ada is a free, open-source programming library for dealing with the Zip compressed archive file format.
The full sources of Zip-Ada are in Ada, compilable on every compiler and for every system (*).

Key features of Zip-Ada:

* Files and streams supported, for archives and entries, for compression and decompression
* Task safe
* Endian-neutral
* Standalone
* Zip methods supported for compression: Reduce, Shrink, Deflate, BZip2, LZMA.
* Zip methods supported for decompression: the above methods, plus: Implode, Deflate64
* Library is in pure Ada 2012 (nothing compiler/system specific), can be used in projects in Ada 2012 and later versions of the language
* Unconditionally portable (*)
* Tests and demos included

The library includes LZMA & BZip2 independant compressor & decompressor pairs
(can be used outside of the Zip archive context).

___

(*) within limits of compiler's provided integer types and target architecture capacity.
"""

project-files = [ "zipada.gpr" ]

executables = [
"comp_zip",
"find_zip",
"bzip2_dec",
"bzip2_enc",
"lzma_dec",
"lzma_enc",
"rezip",
"unzipada",
"zipada",
"zip_dir_list"
]

[origin]
url = "https://sourceforge.net/projects/unzip-ada/files/zipada61.zip"
hashes = ["sha512:54fc9836a9c94107f87f82ce25cfcad9875f6deea8bcd17559f515809198ff8b46c4a1ce1f6b86cc55cc0293b53b54eb5a95eda9f1869529862fd002e0ad8b3f"]

[gpr-set-externals.'case(os)']
macos   = { Zip_OS = "MacOSX" } 
windows = { Zip_OS = "Win64" }
