name = "a0b_stm32f401"
description = "STM32F401 base and SVD package"
website = "https://github.com/godunko/a0b-stm32f401"
version = "0.3.0"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["a0b", "embedded", "svd","stm32", "stm32f4", "stm32f401"]

project-files = ["gnat/a0b_stm32f401.gpr"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = true

[environment]
A0B_TOOLS_BINDING_STARTUP.set = "${CRATE_ROOT}/binding/startup/stm32f401.json"
A0B_TOOLS_SVD.set = "${CRATE_ROOT}/svd/STM32F401.svd"

[[depends-on]]
a0b_armv7m="*"

[[actions]]
type = "test"
directory = "selftest"
command = ["alr", "build"]

[origin]
commit = "fb9d60a5c1300b84f913dc3722fa39aea4d59150"
url = "git+https://github.com/godunko/a0b-stm32f401.git"

