description = "HAC Ada Compiler: a small, quick Ada compiler covering a subset of Ada"
name = "hac"
version = "0.42.0"

authors = ["Gautier de Montmollin"]
website = "https://github.com/zertovitch/hac"
licenses = "MIT"
tags = ["hac", "compiler", "virtual-machine", "native", "semantic", "parser", "advent-of-code"]
maintainers = ["gdemont@hotmail.com"]
maintainers-logins = ["zertovitch"]

long-description = """
&nbsp;<img src="https://hacadacompiler.sourceforge.io/hac_anim.gif" alt="hac logo" width="464" height="auto">

HAC (HAC Ada Compiler) is a small, quickly compiling, open-source Ada compiler, covering a subset of the Ada language.
HAC is perhaps the first open-source (albeit partial) Ada compiler fully programmed in Ada itself.

Features:

* **Quick**: short programming-compilation-run-test cycles.
* Perfect for scripting jobs.
* Compiles Ada sources from any stream - file, internet, editor data, Zip archive, ...
* Compilation leaves zero compilation temp file - all is done in memory!
* Portable, fully programmed in Ada.
* Can be embedded into another software - see the [**LEA**](https://l-e-a.sourceforge.io/) editor - and even exchange data with it - see the `demo/data_exchange/exchange_native_side.adb` demo.
* **Free**, open-source.
"""

project-files = ["hac.gpr"]
executables = ["hac"]

[gpr-externals]
HAC_Build_Mode = ["Debug", "Fast", "Small"]

[origin]
url = "https://sourceforge.net/projects/hacadacompiler/files/hac-0.42.zip"
hashes = ["sha512:170051e4aa5c4bb26203418132fc99a5b48a0266e7f8a1d6c30d41f541b3f78b042875d32bcaa15f1d5dc8098d26a2328cdabb22bbea8d436e1c1f68eb34ffb0"]
