name = "format_strings"
description = "Build and print formatted strings"
version = "0.1.0"

authors = ["Colton Lewis"]
maintainers = ["Colton Lewis <colton.w.lewis@protonmail.com>"]
maintainers-logins = ["cowile"]
licenses = "GPL-3.0-or-later"
website = "https://github.com/cowile/format_strings"
tags = ["format", "formatting", "strings", "templates"]

[build-switches]
"*" . ada_version = "ada2022"

[origin]
commit = "c8d490bac8d3527ed5f07594fbfd03235212e12d"
url = "git+https://github.com/cowile/format_strings.git"

