description = "Middleware layer of the Ada Drivers Library project"
long-description = '''# adl_middleware

Middleware layer of the Ada Drivers Library project.

This crate is a snapshot of the `middleware` of [Ada Drivers
Library](https://github.com/AdaCore/Ada_Drivers_Library/tree/master/middleware).

Any bug report, issue, contribution must be adressed to the [Ada Drivers
Library](https://github.com/AdaCore/Ada_Drivers_Library/) repo.

'''

name = "adl_middleware"
version = "0.4.0"
licenses = "BSD-3-Clause"
authors=["AdaCore"]
website="https://github.com/AdaCore/Ada_Drivers_Library/"
maintainers = ["chouteau@adacore.com"]
maintainers-logins = ["Fabien-Chouteau"]
project-files = ["adl_middleware.gpr"]
tags = ["embedded", "nostd", "fat", "bitmap"]

[[depends-on]]
hal = "^1.0.0"

[build-switches]
"*".style_checks = "no"

[configuration.variables]
Max_Mount_Points = {type = "integer", first = 1, default = 2}
Max_Mount_Name_Length = {type = "integer", first = 1, default = 128}
Max_Path_Length = {type = "integer", first = 1, default = 1024}

[origin]
commit = "aadd86ce7adff45862a329ee8252ad13ba6e0856"
url = "git+https://github.com/Fabien-Chouteau/adl-middleware.git"

