name                        = "adacl_regexp"
description                 = "AdaCL: Regex and SPITBOL Patterns with Wide Character Support"
long-description            = """Regular expression and SPITBOL pattern matching for Ada 2022, with wide character support.

Features:
- Regular Expressions:
  - Generic implementation for any discrete element array
  - Instantiations for String, Wide_String, and Wide_Wide_String
- SPITBOL Patterns:
  - Pattern construction and matching, inspired by Macro-SPITBOL (Robert Dewar)
  - Supports String, Wide_String, and Wide_Wide_String
- Forked from GNAT.Regexp and GNAT.Spitbol with enhanced wide and wide-wide character support

Licensed under GPL-3.0-or-later. Integrates with the Ada Class Library (AdaCL).

Source: [SourceForge](https://sourceforge.net/p/adacl/git/ci/master/tree/adacl_regexp/src/)
Documentation: [GNATdoc](https://adacl.sourceforge.net/gnatdoc/adacl_regexp/index.html)
"""
version                     = "6.3.0"
licenses                    = "GPL-3.0-or-later"
authors                     = ["Martin Krischik <krischik@users.sourceforge.net>"]
maintainers                 = ["Martin Krischik <krischik@users.sourceforge.net>"]
maintainers-logins          = ["krischik"]
website                     = "https://sourceforge.net/projects/adacl/"
tags                        = ["library", "strings", "wide-strings", "search", "regexp", "unicode", "ada2022"]

[build-switches]
"*".ada_version             = "Ada2022"
"*".source_encoding         = "UTF_8"
development.compile_checks  = "Warnings"
development.contracts       = "Yes"
development.debug_info      = "Yes"
development.optimization    = "Debug"
development.runtime_checks  = "Overflow"
release.compile_checks      = "Warnings"
release.contracts           = "No"
release.debug_info          = "No"
release.optimization        = "Performance"
release.runtime_checks      = "Default"
validation.compile_checks   = "Warnings"
validation.contracts        = "Yes"
validation.debug_info       = "Yes"
validation.optimization     = "Debug"
validation.runtime_checks   = "Everything"

[[depends-on]]
adacl                       = "^6.3.0"


[origin]
hashes = [
"sha256:d1f82aba41f039402e75c68efe90c4e3def0eda6ffee1feda7c46ebbf29d2f1b",
"sha512:f865f1b142baabe82c3d178e27015d6671affa477348a38f19bc99c5a747e9de89d94e750f7125e2eec9536b0e994b5c9cd40294b61d875d0f321e8ad7c963c6",
]
url = "https://sourceforge.net/projects/adacl/files/Alire/adacl_regexp-6.3.0.tgz"

