name                = "adacl"
description         = "Ada Class Library"
version             = "5.9.5-dev"
licenses            = "GPL-3.0-or-later"
authors             = ["Martin Krischik <krischik@users.sourceforge.net>"]
maintainers         = ["Martin Krischik <krischik@users.sourceforge.net>"]
maintainers-logins  = ["krischik"]
website             = "https://sourceforge.net/projects/adacl/"
tags                = ["library", "commandline", "trace", "ada-2022"]

[build-switches]

[origin]
hashes = [
"sha256:97b8783dc59305c48a0aa6b467fb83e68c891be21624a37a8f9486ac94af60e3",
"sha512:233a3300532bababcaec4676000953d535829340ff417e95db3b668506ca4f5d7a5352c4affe189ab0668d11978c1d9f0f846c35600452d0fdffad4e7d882366",
]
url = "https://sourceforge.net/projects/adacl/files/Alire/adacl-5.9.5-dev.tgz"

