name = "hp41cx_tools"
description = "Cross-platform tools to supercharge your HP-41CX emulator experience"
long-description = """
## HP-41CX Emulator Tools

Step into the golden era of retro computing with **hp41cx_tools**, a versatile
suite that turbocharges your HP-41CX emulator adventures! Unlike many tools
shackled to Windows, this toolkit runs flawlessly on **macOS**, **Linux**, and
**Windows**, making it the ultimate companion for enthusiasts using the iconic
[PX-41CX](https://paxer.net/PX-41CX/) from Paxer or the sleek
[DM41X](https://www.swissmicros.com/product/dm41x) from SwissMicros. Channel
your inner 1980s programming wizard and master memory dumps and FOCAL source
code with ease.

Built with the precision of **Ada 2022** for unshakeable reliability, these
tools decode and convert data with the finesse of the HP-41CX's legendary
keystrokes. Paired with intuitive **ZShell scripts** for macOS and Linux, the
suite streamlines complex workflows, whether you're on a modern MacBook, a
Linux workstation, or a Windows PC. This cross-platform prowess ensures every
retro computing fan can join the fun, no matter their setup.

### Key Features

- **Memory Dump Decoder**: Transform raw HP-41CX emulator memory dumps into readable FOCAL source code with pinpoint accuracy.
- **Source Code Converter**: Seamlessly convert between PX-41CX and DM41X FOCAL code styles, bridging emulator ecosystems.
- **Unicode Support**: Convert Unicode-encoded FOCAL programs to PX-41CX or DM41X formats, blending vintage charm with modern workflows.
- **Cross-Platform Power**: Runs natively on macOS, Linux, and Windows-unlike many Windows-only alternatives.
- **Open Source**: Hosted on [SourceForge](https://sourceforge.net/p/calculator-scripts/code/ci/master/tree/Tools/hp41cx_tools/src/), ready for you to hack, extend, and share with the retro computing community.
- **Comprehensive Docs**: Explore detailed guides via [GNATdoc](https://calculator-scripts.sourceforge.io/gnatdoc/hp41cx-tools).

### Why You'll Love It

Relive the thrill of programming the HP-41CX, the calculator that defined a
generation of scientific and hobbyist triumphs. Whether you're decoding vintage
memory dumps or crafting new FOCAL programs, **hp41cx_tools** brings the past
to life with unmatched versatility. Join the retro computing revolution and
make your emulator sing-on any desktop OS!
"""
version                     = "1.7.1"
licenses                    = "GPL-3.0-or-later"
authors                     = ["Martin Krischik <krischik@users.sourceforge.net>"]
maintainers                 = ["Martin Krischik <krischik@users.sourceforge.net>"]
maintainers-logins          = ["krischik"]
website                     = "https://calculator-scripts.sourceforge.io/hp41cx-tools/"
tags                        = ["calculator", "tools", "retrocomputing", "ada-2022", "hp-41cx", "dm41x", "px41cx", "cross-platform"]
executables                 = [
    "hp41cx_tools-main",
    "hp41cx_tools-dm41_to_px41",
    "hp41cx_tools-px41_to_dm41",
    "hp41cx_tools-unicode_to_dm41",
    "hp41cx_tools-unicode_to_px41"
]
[build-switches]
development.compile_checks  = "Warnings"
development.contracts       = "Yes"
development.runtime_checks  = "Overflow"
release.compile_checks      = "Warnings"
release.contracts           = "No"
release.runtime_checks      = "Default"
validation.compile_checks   = "Warnings"
validation.contracts        = "Yes"
validation.runtime_checks   = "Everything"

[[depends-on]]
adacl                       = "^6.3.0"
adacl_regexp                = "^6.3.0"
adacl_sar                   = "^6.3.0"


[origin]
hashes = [
"sha256:aed1b078137880fef793e782b4aba996a26a922b0c60e926ae9f9e3ac0a39626",
"sha512:05fa1ad84cf67a5c61666901a55df9d6bcbdda9c8db6f6aeeff00774893b325d18f8089ffc2c3d62094df4bb371c85ff2c811e1b5b3eb6034c69e0fe2c1ae525",
]
url = "https://sourceforge.net/projects/calculator-scripts/files/Alire/hp41cx_tools-1.7.1.tgz"

