name: Check Author

env:
  CHECKS_ORG: alire-project
  CHECKS_REPO: alire-index-checks
  ALR_VERSION: 2.1.0

on:
  pull_request:
    paths:
      - 'index/**.toml'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        # Needed to be able to diff and obtain changed files. Furthermore, we
        # need the full history or else grafted partial branches confuse the
        # changed files detectors.

    - name: Check out alire-index-checks
      uses: actions/checkout@v4
      with:
        repository: ${{env.CHECKS_ORG}}/${{env.CHECKS_REPO}}
        ref: ${{github.base_ref}}
        path: ${{env.CHECKS_REPO}}

    - name: Set up stable `alr`
      uses: alire-project/setup-alire@v5
      with:
        version: ${{env.ALR_VERSION}}

    - name: Test authorship
      run: ${{env.CHECKS_REPO}}/scripts/check-author.sh "${{ github.event.pull_request.user.login }}"
      shell: bash
